name: Invitation to the DevTalkSpace GitHub Community Organization
description: I’d love to be part of this amazing community!
title: "Please invite me to the DevTalkSpace GitHub Community Organization"
labels: [invite me to the community]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What do you like about this community/Why do you want to join?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Feel free to check out other cool repositories of the DevTalkSpace Community [here](https://github.com/DevTalkSpace)